PROJ_DIR = . 

CCFLAGS =
OCFLAGS = -dtypes

INCDIR = $(PROJ_DIR:%=-I %)

CC = gcc $(CCFLAGS) $(INCDIR)
OC = ocamlc $(OCFLAGS) $(INCDIR)
JAVAC = javac

default : language

language :

	ocamlyacc parser.mly;
	ocamllex lexer.mll;
	$(OC) -c ast.mli;
	$(OC) -c scope_stack.mli;
	$(OC) -c parser.mli;
	$(OC) -c parser.ml;
	$(OC) -c lexer.ml;
	$(OC) -c ast.ml;
	$(OC) -c scope_stack.ml;

	rm lexer.ml;
	rm parser.mli;
	rm parser.ml;

clean :
	rm $(PROJ_DIR:%=%/*.cmi) $(PROJ_DIR:%=%/*.cmo) $(PROJ_DIR:%=%/*.cma) \
		$(PROJ_DIR:%=%/*.cmx) $(PROJ_DIR:%=%/*.annot)